name: Build Bench Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar ferramentas
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            live-build \
            debootstrap \
            squashfs-tools \
            xorriso \
            debian-archive-keyring \
            dosfstools \
            mtools

      - name: Verificar ambiente
        run: |
          lb --version
          debootstrap --version
          mksquashfs -version
          xorriso -version
          test -f /usr/share/keyrings/debian-archive-keyring.gpg

      - name: Limpar build anterior
        run: |
          sudo lb clean --purge || true
          sudo rm -rf chroot cache binary bootstrap installer source tmp .build
          sudo rm -f *.iso

      - name: Corrigir live-build Contents
        run: |
          FILE="/usr/lib/live/build/lb_chroot_linux-image"

          sudo sed -i \
            's#${LB_PARENT_MIRROR_CHROOT}/dists/${LB_PARENT_DISTRIBUTION}/Contents-${LB_ARCHITECTURES}.gz#${LB_PARENT_MIRROR_CHROOT}/dists/${LB_PARENT_DISTRIBUTION}/main/Contents-${LB_ARCHITECTURES}.gz#g' \
            "$FILE"

          sudo sed -i \
            's#${LB_MIRROR_CHROOT}/dists/${LB_DISTRIBUTION}/Contents-${LB_ARCHITECTURES}.gz#${LB_MIRROR_CHROOT}/dists/${LB_DISTRIBUTION}/main/Contents-${LB_ARCHITECTURES}.gz#g' \
            "$FILE"

          echo "===== VERIFICANDO CORREÇÃO ====="
          grep -n "Contents-" "$FILE"

      - name: Configurar Debian Live
        run: |
          lb config \
            --mode debian \
            --distribution bookworm \
            --architectures amd64 \
            --archive-areas "main contrib non-free non-free-firmware" \
            --mirror-bootstrap http://deb.debian.org/debian \
            --mirror-binary http://deb.debian.org/debian \
            --mirror-chroot http://deb.debian.org/debian \
            --security false \
            --debian-installer false

      - name: Construir ISO
        run: |
          sudo lb build

      - name: Verificar ISO
        run: |
          echo "===== BENCH LINUX ====="
          ls -lh *.iso
          file *.iso

      - name: Salvar ISO
        uses: actions/upload-artifact@v4
        with:
          name: bench-linux-0.01
          path: "*.iso"
          if-no-files-found: error
